[project]
name = "warera"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.4"
dependencies = [
    "numpy>=2.3.5",
    "pyqt6>=6.10.0",
    "ruff>=0.14.7",
]
